import turtle
turtle.getturtle()
turtle.penup()
turtle.goto(-100, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-90, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-80, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-70, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-60, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-50, 0)
turtle.pendown()
turtle.write("F", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(-20, 0)
turtle.pendown()
turtle.write("U", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(20, 0)
turtle.pendown()
turtle.write("U", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(60, 0)
turtle.pendown()
turtle.write("N", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(70, 0)
turtle.pendown()
turtle.write("N", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(130, 0)
turtle.pendown()
turtle.write("N", move=False, align='left', font=('Arial', 12, 'normal'))
turtle.penup()
turtle.goto(140, 0)
turtle.pendown()
turtle.write("N", move=False, align='left', font=('Arial', 12, 'normal'))
